apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: water-meter
spec:
  encryptedData:
    credentials.json: AgAZJkdLft2DZvbWwPqDa2PWtR0WyBy/U8LG8AvkBL8dp+OEQooOp5cORQHWZ0WT/KnEw8mkN9iJLiEZph6c5B14oMAj9xDrXApGSIx+AMtDJ1Cg0vpjfsC7kQ6fR8v87n3UXKtxRwEbc3WBNb7JuTyoKVkkIUXl65OrGTukxSeVLuhrrdMqHCKNSnfT1UqRB4tcOo+eB0wzAx80XnIGJNPaujDRwYtUFB6hD/BHe5t8PlzboZEy4KDvU2Vk1i9DDclCBp14SmCZ4cuYWW2La6mtlxsT7dOfpM48UGIS2nr1jqWjx6irzzwGesWICketOPJ1ay5uwIZvVVJaKg4X57Pg02YSOFkTVmLwTpVJaWReRd7bLQm+H815nW5hCeLNfZqbeWZfxF9Bx96TAgaPKF2jCNzuM32E5s2fZeSfGqIfUlHDr4pHFE52IcCOBh4xB+ahexShMvmd0Bftgu0rwTgccvKucu99cILP6L+pRJY6Pete+9yR7kZraDizhsvsQGTfUkAOGyZCL6gxi880m2Zpy0naRf5QQ1dTNEvvVNEISsAoIMo41IISe6XkbKcKNvjs7NDwtDdMx5w8/jYNVWhq6JN/fXqG3Optsn+EOTSNcHa/Xv9Pt8BC8yknD7thJ4wzuZaMilF3OE+z6sQGQDpLXwXZtWqIFdE8/FuQHV34nNpbWnM0UphaD+2EMf7a9wgajmtJDwWNnNcGBAXEsNbheUQqEmX8L9BAjgXJCMevQ7I5RLS9IrrCBSTAzjzsxF2w8iUr/lR+qGlqn+bUDCiutbPml3mbzxD2sYcwpEjD4NsedzLEu9Qa0y90qsjQ2PuHzU2ni/QhZj1umWt83WLDX++gyOeolJDsBa2U54ZdWY5sVE06ahC04lV3aGxIurmK7Z7ZHEnsLMzLsfOLgGY0uOB/6/saFhnhSofqGdIS
  template:
    metadata:
      name: cloudflared-credentials
      namespace: water-meter
