apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-url
  namespace: water-meter
spec:
  encryptedData:
    DATABASE_URL: AgBk0RHz8mLBc2lBXULaxpCqucQ5kG2zJHj/y2Cq87hZMt/bDHZOx59v3mv8tdPBgtNoeXyTNNqjwyuZf4MH/8W/Rh8vaSZO6vpzPLBi+VRhLNa7LutxLUAXgLJHHMlp+34zc1rlB87rDUlCzrGhsUhLgOyQ2RavXn4hH8Omektt/pSTuisDlNp9UUrI3dnpQQ6IOH8aHEVswiQTXTwZGyJ/IfkSAOK3RyIeA+IOJN+v5NCw3HcddIWyqf8ovCMJMJwtq34g4WUQXU8g9FxzRUOCah5TEN7qjNY55IyYKbOd18lOl8r13EAI3npB+SZzEasfKp6aOaH7F3T5Vgx3RwnJJH52g+83nX0aMxwZ3RLoV4E1zfcjBNod3EjX50ww//iMXIx/0AWbCBRez/YjSDKsagYG610C1lDDDRAWOzsdNsSEJGPr0o5/lTN4gylXryX/zq5ZlTsslJJ3xBRc1aGYXmXDFLkWWzt1XIe2bGEw3ICfzq+6z+lxNwJyBKC5s4RiYom5+E+7Xg0Mv0wiUHZSUoC6McK4iWNJKG+7CMl0v/6bsZr4/wgMEwKWSp5Yvqw3r2dCUd6z/W8sRQ3QQ8KcxeuzVh7qGTd3lao9iA7rw5XNr6RM3AxmTTzYtccm3pqEF4q56Cj+T0MXUbYjeASZTfG/Zw8+OfZEohblyZqR/mm03KPJGmKu0s1Jfa+OXnQLyxOo8lFwaslt5iKEnOt6ij14jGO+3hjjxAxqlBheA6zxbO7DdI9uw61OriYfV7tZZEu416LmGX1oxvyJRukopfcjOL0AjsRaBKvXUCz1W4mNIC4FZ1mp9MgCHTCZMdXy3D9STWa7AmJ4d4VSsVOEhsr/quO3i84e15s=
  template:
    metadata:
      name: database-url
      namespace: water-meter
