apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-url
  namespace: water-meter
spec:
  encryptedData:
    DATABASE_URL: AgCKiua2SgmeN1yRgzC5g1Mmd7utzgA/Pu22OL3LZX5YAJfSsclzFKCPtYf9IjrvR2piH+uy5A4lwc8XuurgYyIcZ/AovHOVU5HkGetX8joMUofWyvEuoE3xVL8dWqFchnzMts7Lkeg2HWAseZfjtybd3Gu87XiGl9q2eiIjwd3MX1ewP9wgRHyOJxcvqfBvhf1sP7KhSCQbBJofi+KtZ8AgWto957gX4esBPG+xT7GuCZi8d7xt3NDA/v0aT/3JStGiK1eecGCvnx3iiy9Z+gxlxlhidtavrSZfzEMNrvJhagrLwuTg2vw23vFIzYr8xADGqgeB0Tj1W5N+roCxwTkvMveihAkrF+FN9RNCRzAi4vMi7GuKcuGl0NjzUTYxn7mTmB9OKXq6MZJKLqF8kIz8X5xDQebUvYIp6sWCRtlRAfMpmukFW9DxBpYzWJdz2drmm8VKboF6JsY5v8EmjPruLeSymuNCeiDSRFj1mVqAYhCEh1cZQGMynTGQpkQl8lrr8OW/bzAlw0gn1OOsVEDGWXdayld7Uj06jlKjsOBA9JxX/gHApFDfsmpuUA7de5JGd2zJLzagJTcEA/6XyXiFWSkMSzjGmp0xW111O7LmjurDyq4PiIsMO8T7ggXrPgdfzW3/4t3Ewo14Vxxq44fn4hN3ZWk4MBTZZvhLkEZQyEWwhgeK9Vw23JRiSt75JbZmGrKcXNpqtmnBOvTGDVszpLjq/QyVIJIW30z4+wMER9z1qT+o1qKGIed2Ugt+hLiEbrKrFNmItKnr+OT4AvA1fignKXnJzZWcNf7kHSp7SRRyUVzRHKrdbBlnicmHRz8wyv2/NEo/2Hyix0qxuphQB2eeXZ/iPu3xddAk
  template:
    metadata:
      name: database-url
      namespace: water-meter
