"""initial schema

Revision ID: 0ff3aa912e51
Revises: 
Create Date: 2026-08-26 14:02:30.262186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff3aa912e51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('period_end_month', sa.Integer(), nullable=True),
    sa.Column('period_end_year', sa.Integer(), nullable=True),
    sa.Column('total_units_consumed', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_statements_id'), 'billing_statements', ['id'], unique=False)
    op.create_table('leak_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leak_sessions_id'), 'leak_sessions', ['id'], unique=False)
    op.create_table('oracle_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wallet_path', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('wallet_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mi', sa.String(), nullable=True),
    sa.Column('reading', sa.Float(), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_table('leak_main_meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('meter_id', sa.String(), nullable=True),
    sa.Column('meter_sn', sa.String(), nullable=True),
    sa.Column('read_time', sa.DateTime(), nullable=False),
    sa.Column('read_value', sa.Float(), nullable=False),
    sa.Column('flow_time', sa.DateTime(), nullable=True),
    sa.Column('flow_value', sa.Float(), nullable=True),
    sa.Column('register', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['leak_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leak_main_meter_readings_id'), 'leak_main_meter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_leak_main_meter_readings_session_id'), 'leak_main_meter_readings', ['session_id'], unique=False)
    op.create_table('leak_submeter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mi', sa.String(), nullable=False),
    sa.Column('reading', sa.Float(), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['leak_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leak_submeter_readings_id'), 'leak_submeter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_leak_submeter_readings_session_id'), 'leak_submeter_readings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leak_submeter_readings_session_id'), table_name='leak_submeter_readings')
    op.drop_index(op.f('ix_leak_submeter_readings_id'), table_name='leak_submeter_readings')
    op.drop_table('leak_submeter_readings')
    op.drop_index(op.f('ix_leak_main_meter_readings_session_id'), table_name='leak_main_meter_readings')
    op.drop_index(op.f('ix_leak_main_meter_readings_id'), table_name='leak_main_meter_readings')
    op.drop_table('leak_main_meter_readings')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_table('oracle_profiles')
    op.drop_index(op.f('ix_leak_sessions_id'), table_name='leak_sessions')
    op.drop_table('leak_sessions')
    op.drop_index(op.f('ix_billing_statements_id'), table_name='billing_statements')
    op.drop_table('billing_statements')
    # ### end Alembic commands ###
